services:
  dry-datalist-adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: dry-datalist-db
      ADMINER_DESIGN: nette
      UPLOAD_LIMIT: 10G
    labels:
      - "traefik.http.routers.dry-datalist-adminer.rule=Host(`adminer.dry-datalist.localhost`)"
    networks:
      - dev

  dry-datalist-db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/db:/var/lib/mysql
      - ./docker/db_init:/docker-entrypoint-initdb.d
    command: --sql-mode="ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    networks:
      - dev

  dry-datalist-dev:
    build:
      context: https://github.com/TallieuTallieu/dry-docker.git#php8.4
    hostname: docker_app
    volumes:
      - ./:/var/www/html
      - ./docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./docker/xdebug/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:ro
      - ~/.ssh:/root/.ssh:ro
    command: /bin/bash -c 'eval $$(ssh-agent -s) && ssh-add ~/.ssh/id_rsa && composer install && apachectl -D FOREGROUND'
    ports:
      - "80"
    labels:
      - "traefik.http.routers.dry-datalist-dev.rule=Host(`dry-datalist.localhost`)"
    networks:
      - dev

networks:
  dev:
    external: true
